#!/usr/bin/env node
/**
 * src/schedule.mjs — Phase 5: register (or just PRINT) the nightly Windows task.
 *
 *   node src/schedule.mjs              # print the schtasks command — ARMS NOTHING (default)
 *   node src/schedule.mjs --install    # actually create the daily 04:00 task
 *   node src/schedule.mjs --status     # query the task
 *   node src/schedule.mjs --uninstall  # remove it
 *
 * Registering a scheduled task is persistent system config — a deliberate,
 * explicit step. So the DEFAULT does nothing but show you the exact command;
 * nothing gets armed unless you (a human) run --install on purpose.
 *
 * Note: a 04:00 daily task only fires if the machine is awake then. If the box
 * sleeps, add /RL or a wake timer via Task Scheduler, or run --now by hand —
 * the no-change short-circuit makes catch-up runs cheap.
 */

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const CANARY_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const TASK = 'vugg-canary-nightly';
const TIME = '04:00';

const nodeExe = process.execPath;
const sweep = path.join(CANARY_ROOT, 'src', 'sweep.mjs');
const logFile = path.join(CANARY_ROOT, 'logs', '_nightly.log');
const wrapper = path.join(CANARY_ROOT, 'run-nightly.cmd');
// schtasks /tr has a length limit and chokes on embedded && — so we point the
// task at a tiny generated wrapper .cmd (short path, no quoting hazards) that
// cds into the repo and runs the sweep. The wrapper is machine-specific
// (absolute paths) and gitignored; --install (re)writes it.
const wrapperBody =
  `@echo off\r\n` +
  `rem auto-generated by src/schedule.mjs — the nightly vugg-canary sweep\r\n` +
  `cd /d "${CANARY_ROOT}"\r\n` +
  `"${nodeExe}" "${sweep}" --now >> "${logFile}" 2>&1\r\n`;
// /tr must be a LITERALLY-quoted path: the wrapper lives under "...\Local
// Storage\..." and schtasks splits an unquoted /tr value on the space, storing
// Execute=C:\Users\baals\Local (→ 0x80070002 file-not-found at 04:00). The
// embedded quotes survive into the stored task action as the executable path.
const createArgs = ['/create', '/tn', TASK, '/sc', 'DAILY', '/st', TIME, '/tr', `"${wrapper}"`, '/f'];

const mode = process.argv[2] || '--print';

if (mode === '--print' || mode === '--help' || mode === '-h') {
  console.log(`vugg-canary scheduler (Phase 5) — nothing armed.\n`);
  console.log(`A daily ${TIME} task "${TASK}" would run the wrapper ${wrapper}, which does:`);
  console.log(wrapperBody.split('\r\n').filter(Boolean).map((l) => `  ${l}`).join('\n') + '\n');
  console.log(`Arm it:     node src/schedule.mjs --install`);
  console.log(`  (equiv:   schtasks ${createArgs.map((a) => (/\s/.test(a) ? `"${a}"` : a)).join(' ')})`);
  console.log(`Check:      node src/schedule.mjs --status`);
  console.log(`Remove:     node src/schedule.mjs --uninstall`);
} else if (mode === '--install') {
  fs.mkdirSync(path.join(CANARY_ROOT, 'logs'), { recursive: true });
  fs.writeFileSync(wrapper, wrapperBody);
  execFileSync('schtasks', createArgs, { stdio: 'inherit' });
  console.log(`[schedule] armed "${TASK}" daily at ${TIME} → ${wrapper}. (--status to verify, --uninstall to remove)`);
} else if (mode === '--status') {
  try { execFileSync('schtasks', ['/query', '/tn', TASK, '/v', '/fo', 'LIST'], { stdio: 'inherit' }); }
  catch { console.log(`[schedule] task "${TASK}" not found — not armed.`); }
} else if (mode === '--uninstall') {
  try { execFileSync('schtasks', ['/delete', '/tn', TASK, '/f'], { stdio: 'inherit' }); console.log(`[schedule] removed "${TASK}".`); }
  catch { console.log(`[schedule] task "${TASK}" not found — nothing to remove.`); }
} else {
  console.error(`unknown mode "${mode}" — use --print | --install | --status | --uninstall`);
  process.exit(2);
}
